service: dynamocrudoperations
frameworkVersion: '2'
custom:
  settings:
    post_table: posts
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region : us-east-1
  environment: ${self:custom.settings}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:updateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.post_table}"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /post
          method: post
  getpost:
      handler: handler.getpost
      events:
        - httpApi:
            path: /getpost
            method: get

resources:
  Resources:
    posttable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id" 
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.post_table} 